CREATE TABLE IF NOT EXISTS team(
     id INTEGER  PRIMARY KEY AUTO_INCREMENT,
     name VARCHAR(20) NOT NULL,
     division VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
    id INTEGER  PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL
);